//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIclient.MiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="musicdata", Namespace="http://schemas.datacontract.org/2004/07/MI")]
    [System.SerializableAttribute()]
    public partial class musicdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstrumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KaraokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LyricField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string avatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bAuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cSingerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dPublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eGenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string voteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emotion {
            get {
                return this.EmotionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmotionField, value) != true)) {
                    this.EmotionField = value;
                    this.RaisePropertyChanged("Emotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instrument {
            get {
                return this.InstrumentField;
            }
            set {
                if ((object.ReferenceEquals(this.InstrumentField, value) != true)) {
                    this.InstrumentField = value;
                    this.RaisePropertyChanged("Instrument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Karaoke {
            get {
                return this.KaraokeField;
            }
            set {
                if ((object.ReferenceEquals(this.KaraokeField, value) != true)) {
                    this.KaraokeField = value;
                    this.RaisePropertyChanged("Karaoke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang {
            get {
                return this.LangField;
            }
            set {
                if ((object.ReferenceEquals(this.LangField, value) != true)) {
                    this.LangField = value;
                    this.RaisePropertyChanged("Lang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lyric {
            get {
                return this.LyricField;
            }
            set {
                if ((object.ReferenceEquals(this.LyricField, value) != true)) {
                    this.LyricField = value;
                    this.RaisePropertyChanged("Lyric");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aTitle {
            get {
                return this.aTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.aTitleField, value) != true)) {
                    this.aTitleField = value;
                    this.RaisePropertyChanged("aTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string avatar {
            get {
                return this.avatarField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarField, value) != true)) {
                    this.avatarField = value;
                    this.RaisePropertyChanged("avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bAuthor {
            get {
                return this.bAuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.bAuthorField, value) != true)) {
                    this.bAuthorField = value;
                    this.RaisePropertyChanged("bAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cSinger {
            get {
                return this.cSingerField;
            }
            set {
                if ((object.ReferenceEquals(this.cSingerField, value) != true)) {
                    this.cSingerField = value;
                    this.RaisePropertyChanged("cSinger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dPublish {
            get {
                return this.dPublishField;
            }
            set {
                if ((object.ReferenceEquals(this.dPublishField, value) != true)) {
                    this.dPublishField = value;
                    this.RaisePropertyChanged("dPublish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eGenre {
            get {
                return this.eGenreField;
            }
            set {
                if ((object.ReferenceEquals(this.eGenreField, value) != true)) {
                    this.eGenreField = value;
                    this.RaisePropertyChanged("eGenre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vote {
            get {
                return this.voteField;
            }
            set {
                if ((object.ReferenceEquals(this.voteField, value) != true)) {
                    this.voteField = value;
                    this.RaisePropertyChanged("vote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fauloutofmemory", Namespace="http://schemas.datacontract.org/2004/07/MI")]
    [System.SerializableAttribute()]
    public partial class fauloutofmemory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lydoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lydo {
            get {
                return this.lydoField;
            }
            set {
                if ((object.ReferenceEquals(this.lydoField, value) != true)) {
                    this.lydoField = value;
                    this.RaisePropertyChanged("lydo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="singerdata", Namespace="http://schemas.datacontract.org/2004/07/MI")]
    [System.SerializableAttribute()]
    public partial class singerdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aSingernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bSingerrealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cSingerdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eSingercomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fSingeravatarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aSingername {
            get {
                return this.aSingernameField;
            }
            set {
                if ((object.ReferenceEquals(this.aSingernameField, value) != true)) {
                    this.aSingernameField = value;
                    this.RaisePropertyChanged("aSingername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bSingerreal {
            get {
                return this.bSingerrealField;
            }
            set {
                if ((object.ReferenceEquals(this.bSingerrealField, value) != true)) {
                    this.bSingerrealField = value;
                    this.RaisePropertyChanged("bSingerreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cSingerday {
            get {
                return this.cSingerdayField;
            }
            set {
                if ((object.ReferenceEquals(this.cSingerdayField, value) != true)) {
                    this.cSingerdayField = value;
                    this.RaisePropertyChanged("cSingerday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dCountry {
            get {
                return this.dCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.dCountryField, value) != true)) {
                    this.dCountryField = value;
                    this.RaisePropertyChanged("dCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eSingercom {
            get {
                return this.eSingercomField;
            }
            set {
                if ((object.ReferenceEquals(this.eSingercomField, value) != true)) {
                    this.eSingercomField = value;
                    this.RaisePropertyChanged("eSingercom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fSingeravatar {
            get {
                return this.fSingeravatarField;
            }
            set {
                if ((object.ReferenceEquals(this.fSingeravatarField, value) != true)) {
                    this.fSingeravatarField = value;
                    this.RaisePropertyChanged("fSingeravatar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaultMsg", Namespace="http://schemas.datacontract.org/2004/07/MI")]
    [System.SerializableAttribute()]
    public partial struct CustomFaultMsg : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiService.IMiService")]
    public interface IMiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/getall", ReplyAction="http://tempuri.org/IMiService/getallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIclient.MiService.fauloutofmemory), Action="http://tempuri.org/IMiService/getallfauloutofmemoryFault", Name="fauloutofmemory", Namespace="http://schemas.datacontract.org/2004/07/MI")]
        MIclient.MiService.musicdata[] getall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Hasmusic", ReplyAction="http://tempuri.org/IMiService/HasmusicResponse")]
        bool Hasmusic(string music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getid", ReplyAction="http://tempuri.org/IMiService/GetidResponse")]
        MIclient.MiService.musicdata[] Getid(string music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Gettitle", ReplyAction="http://tempuri.org/IMiService/GettitleResponse")]
        MIclient.MiService.musicdata[] Gettitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getauthor", ReplyAction="http://tempuri.org/IMiService/GetauthorResponse")]
        MIclient.MiService.musicdata[] Getauthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getlyric", ReplyAction="http://tempuri.org/IMiService/GetlyricResponse")]
        MIclient.MiService.musicdata[] Getlyric(string lyric);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getgenre", ReplyAction="http://tempuri.org/IMiService/GetgenreResponse")]
        MIclient.MiService.musicdata[] Getgenre(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getemotion", ReplyAction="http://tempuri.org/IMiService/GetemotionResponse")]
        string Getemotion(string emotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getins", ReplyAction="http://tempuri.org/IMiService/GetinsResponse")]
        MIclient.MiService.musicdata[] Getins(string ins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getpub", ReplyAction="http://tempuri.org/IMiService/GetpubResponse")]
        MIclient.MiService.musicdata[] Getpub(string pub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getkaraoke", ReplyAction="http://tempuri.org/IMiService/GetkaraokeResponse")]
        MIclient.MiService.musicdata[] Getkaraoke(string karaoke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getlang", ReplyAction="http://tempuri.org/IMiService/GetlangResponse")]
        MIclient.MiService.musicdata[] Getlang(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/musickaraoke", ReplyAction="http://tempuri.org/IMiService/musickaraokeResponse")]
        MIclient.MiService.musicdata[] musickaraoke(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/musicnhacsi", ReplyAction="http://tempuri.org/IMiService/musicnhacsiResponse")]
        MIclient.MiService.musicdata[] musicnhacsi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/musiccasi", ReplyAction="http://tempuri.org/IMiService/musiccasiResponse")]
        MIclient.MiService.musicdata[] musiccasi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/musicloi", ReplyAction="http://tempuri.org/IMiService/musicloiResponse")]
        MIclient.MiService.musicdata[] musicloi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/musicten", ReplyAction="http://tempuri.org/IMiService/musictenResponse")]
        MIclient.MiService.musicdata[] musicten(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Getsinger", ReplyAction="http://tempuri.org/IMiService/GetsingerResponse")]
        MIclient.MiService.singerdata[] Getsinger(string singerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/gettop", ReplyAction="http://tempuri.org/IMiService/gettopResponse")]
        MIclient.MiService.musicdata[] gettop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/setvote", ReplyAction="http://tempuri.org/IMiService/setvoteResponse")]
        void setvote(int musicid, int vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/getvote", ReplyAction="http://tempuri.org/IMiService/getvoteResponse")]
        decimal getvote(int musicid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Addmusic", ReplyAction="http://tempuri.org/IMiService/AddmusicResponse")]
        void Addmusic(MIclient.MiService.musicdata music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Editmusic", ReplyAction="http://tempuri.org/IMiService/EditmusicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIclient.MiService.CustomFaultMsg), Action="http://tempuri.org/IMiService/EditmusicCustomFaultMsgFault", Name="CustomFaultMsg", Namespace="http://schemas.datacontract.org/2004/07/MI")]
        void Editmusic(int musicid, MIclient.MiService.musicdata music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiService/Deletemusic", ReplyAction="http://tempuri.org/IMiService/DeletemusicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIclient.MiService.CustomFaultMsg), Action="http://tempuri.org/IMiService/DeletemusicCustomFaultMsgFault", Name="CustomFaultMsg", Namespace="http://schemas.datacontract.org/2004/07/MI")]
        void Deletemusic(int musicid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServiceChannel : MIclient.MiService.IMiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServiceClient : System.ServiceModel.ClientBase<MIclient.MiService.IMiService>, MIclient.MiService.IMiService {
        
        public MiServiceClient() {
        }
        
        public MiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MIclient.MiService.musicdata[] getall() {
            return base.Channel.getall();
        }
        
        public bool Hasmusic(string music) {
            return base.Channel.Hasmusic(music);
        }
        
        public MIclient.MiService.musicdata[] Getid(string music) {
            return base.Channel.Getid(music);
        }
        
        public MIclient.MiService.musicdata[] Gettitle(string title) {
            return base.Channel.Gettitle(title);
        }
        
        public MIclient.MiService.musicdata[] Getauthor(string author) {
            return base.Channel.Getauthor(author);
        }
        
        public MIclient.MiService.musicdata[] Getlyric(string lyric) {
            return base.Channel.Getlyric(lyric);
        }
        
        public MIclient.MiService.musicdata[] Getgenre(string genre) {
            return base.Channel.Getgenre(genre);
        }
        
        public string Getemotion(string emotion) {
            return base.Channel.Getemotion(emotion);
        }
        
        public MIclient.MiService.musicdata[] Getins(string ins) {
            return base.Channel.Getins(ins);
        }
        
        public MIclient.MiService.musicdata[] Getpub(string pub) {
            return base.Channel.Getpub(pub);
        }
        
        public MIclient.MiService.musicdata[] Getkaraoke(string karaoke) {
            return base.Channel.Getkaraoke(karaoke);
        }
        
        public MIclient.MiService.musicdata[] Getlang(string lang) {
            return base.Channel.Getlang(lang);
        }
        
        public MIclient.MiService.musicdata[] musickaraoke(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang) {
            return base.Channel.musickaraoke(timtheo, loctheo, thoigian, quocgia, tamtrang);
        }
        
        public MIclient.MiService.musicdata[] musicnhacsi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang) {
            return base.Channel.musicnhacsi(timtheo, loctheo, thoigian, quocgia, tamtrang);
        }
        
        public MIclient.MiService.musicdata[] musiccasi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang) {
            return base.Channel.musiccasi(timtheo, loctheo, thoigian, quocgia, tamtrang);
        }
        
        public MIclient.MiService.musicdata[] musicloi(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang) {
            return base.Channel.musicloi(timtheo, loctheo, thoigian, quocgia, tamtrang);
        }
        
        public MIclient.MiService.musicdata[] musicten(string timtheo, string loctheo, string thoigian, string quocgia, string tamtrang) {
            return base.Channel.musicten(timtheo, loctheo, thoigian, quocgia, tamtrang);
        }
        
        public MIclient.MiService.singerdata[] Getsinger(string singerid) {
            return base.Channel.Getsinger(singerid);
        }
        
        public MIclient.MiService.musicdata[] gettop() {
            return base.Channel.gettop();
        }
        
        public void setvote(int musicid, int vote) {
            base.Channel.setvote(musicid, vote);
        }
        
        public decimal getvote(int musicid) {
            return base.Channel.getvote(musicid);
        }
        
        public void Addmusic(MIclient.MiService.musicdata music) {
            base.Channel.Addmusic(music);
        }
        
        public void Editmusic(int musicid, MIclient.MiService.musicdata music) {
            base.Channel.Editmusic(musicid, music);
        }
        
        public void Deletemusic(int musicid) {
            base.Channel.Deletemusic(musicid);
        }
    }
}
